language: scala
scala:
   - 2.12.7
script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts clean test
jdk:
    - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier

