language: scala
scala:
   - 2.12.3
   - 2.11.11
script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts clean test cucumber
jdk:
    - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier

